### ISSUE TITLE
First non-trivial tutorial example does not parse

### ISSUE THREAD

**Issue by keithy** [hvaldecantos/trygve-tutorial#1]
Page 9 of the tutorial (trygve ground zero) the example does not parse!?

```
        int a, b
	a = 1, b = 1
	System.out.println(a == b)
```

K.

**Comment by hvaldecantos** [comment]
It was resolved here: https://github.com/jcoplien/trygve/issues/117
I've also added the 4.2 example d9e4a81546ac584f422dbf21fddb4fc1e3c558a1
Thanks!
